# Generated by Django 2.2.5 on 2019-10-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
        migrations.AddField(
            model_name='profile',
            name='blog_banner',
            field=models.ImageField(default='blog_banner_pics/default_blog_banner.jpeg', upload_to='blog_banner_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blog_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
