# Generated by Django 2.2.5 on 2019-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191002_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/defaultpropic.jpg', upload_to='profile_pics/', verbose_name='Upload your profile picture'),
        ),
    ]
