# Generated by Django 2.2.5 on 2019-10-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191002_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blog_banner',
            field=models.ImageField(default='blog_banner_pics/default_blog_banner.jpg', upload_to='blog_banner_pics/'),
        ),
    ]
