# Generated by Django 2.2.5 on 2019-10-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191004_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blog_banner',
            field=models.ImageField(default='blog_banner_pics/default_blog_banner1.jpg', upload_to='blog_banner_pics/'),
        ),
    ]
