# Generated by Django 2.2.5 on 2019-10-02 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('post_title', models.CharField(max_length=120)),
                ('post_image', models.ImageField(default='blogpost_pics/default_blog_post.jpg', upload_to='blogpost_pics/')),
                ('post_description', models.TextField(max_length=1000)),
                ('publish_status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=15)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
    ]
