# Generated by Django 2.2.5 on 2019-10-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_reaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
