# Generated by Django 2.2.5 on 2019-10-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
