# Generated by Django 2.2.5 on 2019-10-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20191004_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
