# Generated by Django 2.2.5 on 2019-10-04 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0037_reaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
