# Generated by Django 2.2.5 on 2019-10-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20191004_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likeable',
        ),
    ]
